### ISSUE TITLE
HelmRepository not updated

### ISSUE THREAD

**Issue by genofire** [woodpecker-ci/helm#20]
the current version over woodpecker-server has no stateful-set yet.

does the CI-Pipeline works like expacted?

**Comment by anbraten** [comment]
We released a new version.

**Comment by CrimsonFez** [comment]
This is still an issue. The version in the repo at https://woodpecker-ci.org/ is older and doesn't have the stateful set instead of deployment

**Comment by brianclemens** [comment]
Yep, @anbraten if I'm looking at https://ci.woodpecker-ci.org/woodpecker-ci/helm correctly it seems the chart isn't getting pushed to the helm repo because it's set to do that only on tag, and the chart is being updated without doing so?
